### ISSUE TITLE
quick note on docstring parser stuff from slack

### ISSUE THREAD

**Issue by ym-han** [wenkokke/talon-cheatsheet#2]
This is what aegis said on Slack about trying to parse docstrings; just passing it along in case relevant:

"We've talked about it briefly but there's definitely no standard for how talon docstrings should look yet"
 "knausj doesn't really have magic docstrings that need parsing yet, and probably shouldn't do that until we come up with a standard for it"

**Comment by wenkokke** [comment]
I put the docstring parser in by request, so that we could try out that particular format :)
